### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#10]
Все собранные файлы: index.html и build.js; медия файлы: шрифты и картинки; должны быть в папке public(можно и по другому назвать), а не в корне проекта.

**Comment by Burize** [comment]
Да, и ненужно CSS собирать в отдельный файл через extractTextPlugin - все стили также должны находиться в js сборке.

**Comment by ValentinZadorozhnyy** [comment]
Исправлено
