### ISSUE TITLE
education и experience

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#13]
Весь текст захардкожен) Если появится необходимость добавить новый текст, то что тогда?) Нужно сделать более универсальным

**Comment by ValentinZadorozhnyy** [comment]
В миксине в index.pug изменяется параметр row, следовательно количество статей увеличивается.

**Comment by Zarwlar** [comment]
Речь идёт об возможности изменить контент, а не о количестве абзацев)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено
