### ISSUE TITLE
Проект не запускается

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#19]
Сейчас в конфиге вебпака указано
   ` context: __dirname + '\\pre_relise',`
Из-за этого возникает ошибка 
![image](https://user-images.githubusercontent.com/26929933/33134017-2df4cf74-cfd1-11e7-8a81-c425bb529ca2.png)
\\ нужно заменить на /

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
