### ISSUE TITLE
Pixel Perfect

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#2]
Не сходится макет по Pixel Perfect) Напиши ещё плз коэффициент, с которым ты сравнивал)
![image](https://user-images.githubusercontent.com/26929933/31621978-4ffff0fe-b2c5-11e7-89e1-c648def0bb95.png)
![image](https://user-images.githubusercontent.com/26929933/31622094-a6ee76f6-b2c5-11e7-8f9f-726e03f520b3.png)

**Comment by ValentinZadorozhnyy** [comment]
Переделал сегодня макет с PixelPerfect, выложил его.  Прилагаю отрисованные скрины с параметрами.

![pixel1](https://user-images.githubusercontent.com/31644547/31668447-6cb5c04a-b37c-11e7-8b2c-b4fa5a8a6cbf.jpg)
![pixel2](https://user-images.githubusercontent.com/31644547/31668454-7151af6a-b37c-11e7-96f8-fd3a2321a3b3.jpg)

**Comment by Zarwlar** [comment]
У меня что-то страшное произшло с макетом)
![image](https://user-images.githubusercontent.com/26929933/31705099-409a4296-b40e-11e7-80a9-c3b92b44d4d7.png)

**Comment by ValentinZadorozhnyy** [comment]
Это связано с тем, что при верстке с PixelPerfect был вынужден увеличить правую колонку под размеры шаблона. Теперь она не помещается в вашем экране, следовательно колонка начинает сжиматься.
![default](https://user-images.githubusercontent.com/31644547/31707372-54be3388-b416-11e7-8d8b-d7abd374e6b6.png)

**Comment by ValentinZadorozhnyy** [comment]
У меня все отображается нормально.
![2](https://user-images.githubusercontent.com/31644547/31707420-77aeed10-b416-11e7-96d2-ee494c94f722.jpg)

**Comment by Zarwlar** [comment]
У меня всё равно "плывёт" макет. Скинь, пожалуйста, свой скриншот вёрстки с наложенным через PerfectPixel макетом) Как вот этот)
![image](https://user-images.githubusercontent.com/26929933/33137037-68b534e8-cfd9-11e7-9884-1db01312d736.png)

**Comment by ValentinZadorozhnyy** [comment]
![2017-11-25 15-07-16](https://user-images.githubusercontent.com/31644547/33231663-d5d9c4ae-d22b-11e7-87e8-16b9f005cef3.png)
![2017-11-25 15-07-24](https://user-images.githubusercontent.com/31644547/33231664-d96a1fb0-d22b-11e7-9411-6fbf83f8b33b.png)
![2017-11-25 15-07-26](https://user-images.githubusercontent.com/31644547/33231665-dc6700a2-d22b-11e7-9bf8-7b246332a0e4.png)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
