### ISSUE TITLE
Элементы не выровнены?

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#21]
Я не знаю, только ли у меня так, но нужно проверить и исправить, если так не только у меня) Для измерения использовался Page Ruler
![image](https://user-images.githubusercontent.com/26929933/33134464-5db783a4-cfd2-11e7-8f25-0f3e2a116865.png)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
