### ISSUE TITLE
Странный БЭМ

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#22]
![image](https://user-images.githubusercontent.com/26929933/33134598-bfbaadd8-cfd2-11e7-9f6a-f37e38b7aa05.png)
Сейчас здесь есть: 
блок education,
блок education-block,
блок eduction-content,
блок education-title,
элементы education__*
А по факту, у тебя должен был быть блок education, внутри которого должны быть
элементы. Плюс содержимое educationSection нужно инкапуслировать в какой-нибудь элемент education, например.
Иначе мы имеем плоскую структуру, хотя в макете можно увидеть структуру)
Всё вышеперечисленное справедливо и для experience

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
