### ISSUE TITLE
Ещё БЭМ

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#23]
`div(class=options.classname+"-content-rightcolum")`

rightcolum выступает в роли модификатора, но объявлен не согласно нотации БЭМ.
В целом, нужно лучше разобраться в БЭМе)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.

**Comment by Zarwlar** [comment]
Исправь ещё плиз имена. Т.е. rightcolumn и leftcolumn не должно быть, они вообще никакому код стайлу не соответствуют. Здесь речь не столько о БЭМе, сколько вообще о код стайле

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
