### ISSUE TITLE
education.pug и experience.pug

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#25]
В целом структура должна быть такая:
Мы передаём в миксим (например в education) массив данных, а он нам выдаёт соответствующее количество блоков с контентом. Сейчас у тебя захардкожено так, что в education мы имеем строго 4 блока одинакового контента, а в блоке experience мы имеем строго 3 блока одинакового контента

**Comment by Zarwlar** [comment]
contact.pug туда же

**Comment by Zarwlar** [comment]
software.pug тоже нуждается в похожем рефакторинге

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
