### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#3]
очень минималистичный `package.json`
```
{
  "name": "proba",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build":"webpack"
  },
  "author": "",
  "license": "ISC"
}
```
Основное предназначение (ну или по крайней мере одно из основных) этого файла в том, что в нем указываются используемые при разработки ( `devdependencies` ) и при выполнении ( `dependencies` ) модули. Когда делаешь npm -i можно добавлять атрибут `--save-dev` или `--save` и тогда устанавливаемый модуль будет  записываться в соответствующее поле в `package.json` . 

У тебя в node-modules есть все необходимое для сборки проекта, но чтобы мы смогли его запустить нам нужно установить все используемые модули. Для этого их нужно указать в `package.json`

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
