### ISSUE TITLE
При работе резины начинает кривиться вёрстка

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#30]
У блоки education и experience не отцентровываются, а куда-то едут.
При меньшем разрешении это заметно лучше всего, но искривления происходят сразу, после того, как мы вместо 2 колонок получаем одну
![image](https://user-images.githubusercontent.com/26929933/33137480-a63559f0-cfda-11e7-9230-744ce9cb0c89.png)

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.

**Comment by Zarwlar** [comment]
Как-то не очень :(
![image](https://user-images.githubusercontent.com/26929933/33518183-771fa300-d7c3-11e7-9882-31fe66c50180.png)

**Comment by ValentinAlexandrovich** [comment]
Для этих двух блоков нужно уточнение, как лучше их отобразить? Выровнять по центру контакт будет достаточно? Вспомнил пороль от своего аккаунта, поэтому сменилась картинка)

**Comment by ValentinAlexandrovich** [comment]
Исправлено. 
![2017-12-09 22-50-50](https://user-images.githubusercontent.com/31854808/33797062-b2b76022-dd33-11e7-838d-7edc7407980d.png)
