### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#33]
При комментировании можно ссылку на issue оставлять через решетку (#) так будет легче посмотреть что конкретно было исправлено. 

Чем больше коммитов, тем лучше. Даже если issue требует изменения 1 строчки в коде, то нормально коммитить это действие: 1 issue - 1 коммит .  Так будет очень просто понять исправлено ли issue или нет.

**Comment by Burize** [comment]
Добавь еще ссылку плиз на github pages в  readme.

**Comment by ValentinAlexandrovich** [comment]
Принято, ссылка добавлена.
