### ISSUE TITLE
все переменные (кроме глобальных) должны быть заимпорчены (import) в кадом файле в котором они используются

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#34]
![image](https://user-images.githubusercontent.com/22253666/33473039-637f40ac-d6a7-11e7-9573-0937182efed9.png)

Так нельзя делать. Да, сейчас может показаться лишнем, что нужно будет вместо одного index.pug импортить label во всех остальных файлах,  но так правильно, иначе сложно понять откуда взялся этот миксин. Представь если бы это был большой проект с кучей модулей. Причем используя вебпак там не должно быть дублирования кода этого миксина в каждом файле.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
