### ISSUE TITLE
background-position 

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#35]
![image](https://user-images.githubusercontent.com/22253666/33473311-8118b4b2-d6a8-11e7-85e0-8713d58a4745.png)

А почему было принято решение задавать position в rem? - Можно было же задать в процентах. При таком подходе иконки при изменении font-size у html будут скакать. Ну или просто уедут ...

 
![image](https://user-images.githubusercontent.com/22253666/33473387-d9834c70-d6a8-11e7-91cd-8c2a830b5544.png)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
