### ISSUE TITLE
Сделать импорт стилей динамическим

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#42]
Сейчас у тебя в style.styl весит вот такая портянка. При добавлении нового кода мы **должны не забыть** пути до стилей нового блока в этот файл. В противном случае нас ждёт головная боль. Нужно придумать реализовать более универсальное решение
![image_2017-12-03_00-36-50](https://user-images.githubusercontent.com/26929933/33522681-f3fb3702-d824-11e7-8a0d-9199d2a75e08.png)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
