### ISSUE TITLE
Прилип знак education

### ISSUE THREAD

**Issue by Zarwlar** [ValentinAlexandrovich/cv#48]
А как это выглядит у тебя?) У меня вот так:
![image](https://user-images.githubusercontent.com/26929933/34864692-16b3a552-f7a8-11e7-9d23-eb8e6425851b.png)

**Comment by ValentinAlexandrovich** [comment]
Приложу пока скрины с различными разрешениями
![2018-01-16 12-35-06](https://user-images.githubusercontent.com/31854808/34973658-838a4b02-fabb-11e7-8d5d-e9f6c29add36.png)
![2018-01-16 12-35-23](https://user-images.githubusercontent.com/31854808/34973659-83b10bac-fabb-11e7-8c30-bcb27693ed5c.png)
![2018-01-16 12-35-37](https://user-images.githubusercontent.com/31854808/34973661-83ee1466-fabb-11e7-8d60-7ae10d5b654e.png)
![2018-01-16 12-35-53](https://user-images.githubusercontent.com/31854808/34973662-8411d46e-fabb-11e7-8338-4d15d446dd6c.png)
![2018-01-16 12-36-08](https://user-images.githubusercontent.com/31854808/34973663-84348f54-fabb-11e7-8979-227d105210c7.png)
![2018-01-16 12-39-04](https://user-images.githubusercontent.com/31854808/34973664-847bea8e-fabb-11e7-8b8b-d1b529551e4a.png)
![2018-01-16 12-39-22](https://user-images.githubusercontent.com/31854808/34973665-84a18474-fabb-11e7-8d85-fcd42f8e06c2.png)
![2018-01-16 12-39-38](https://user-images.githubusercontent.com/31854808/34973666-84f118f4-fabb-11e7-9ed2-31ffbdb76728.png)

**Comment by ValentinAlexandrovich** [comment]
Возможно это было исправлено в процессе рефакторинга, пока ишьюс закрыать не буду, проверю в офисе на Full HD мониторе, если все норм закрою ишьюс.

**Comment by Zarwlar** [comment]
> Можешь уточнить при каком разрешении экрана это присходит, у меня все нормально показывает

У меня так вёрстка выглядела на экране ноутбука

**Comment by ValentinAlexandrovich** [comment]
![2018-01-18 10-42-08](https://user-images.githubusercontent.com/31854808/35079799-44796236-fc3c-11e7-9089-62737365b64a.png)
Прикладываю скриншот.
