### ISSUE TITLE
font-family

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#6]
font-family задан не правильно. В стандартах есть подробный пример.

**Comment by ValentinZadorozhnyy** [comment]
Исправлено

**Comment by Burize** [comment]
![image](https://user-images.githubusercontent.com/22253666/33471801-8f943496-d6a1-11e7-8211-13b77b39cc01.png)

Много где не по стандартам задан (я к тому что нужно задавать 2 запасных шрифта по мимо основного).

**Comment by ValentinAlexandrovich** [comment]
Исправлено
