### ISSUE TITLE
Названия модификаторов

### ISSUE THREAD

**Issue by Maksimus-Prime** [ValentinAlexandrovich/cv#60]
В риззоме есть соглашение об именовании
https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0l/
и согласно ему 
software-programm__line_check
software-programm__line_check**ed**
Также прочти про виды модификаторов (на собесе тоже будет): ключ-значение и булевы, и напиши здесь когда использовать одни, а когда другие
Вот здесь ты в модификаторе experience ты задаешь картинку, но твой модификатор ничего не говорит своим названием, гораздо лучше будет назвать его icon и у него будет значение experience
Про именование в общем хорошо написано в книге Совершенный код, очень советую тебе его начинать читать, там очень много хороших практик
header__wrapper_experience
header__wrapper_**icon_experience**

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
Булевые модификаторы используют, когда важно только наличие или отсутствие модификатора, а его значение несущественно(selected, focused и т.д.). Считается, что при наличии булевого модификатора у сущности его значение равно true.
Структура имени модификатора :
имя-блока_имя-модификатора;
имя-блока__имя-элемента_имя-модификатора.

Ключ-значение используют, когда важно значение модификатора, в нашем случае как раз иконка является ключом а experience его значением.
Структура  имени модификатора соответствует схеме:
имя-блока_имя-модификатора_значение-модификатора;
имя-блока__имя-элемента_имя-модификатора_значение-модификатора.

**Comment by ValentinAlexandrovich** [comment]
Книжку уже закинул на телефон - буду читать, спасибо за инфу)
