### ISSUE TITLE
Длинный заголовок ломает header

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/cv#61]
Иконка не должна деформироваться. Текст не должен выползать за край элемента.
![r1](https://user-images.githubusercontent.com/31949379/36652622-7bb77c1e-1ae2-11e8-8bb4-db0c384ebce3.JPG)

**Comment by Geksanit** [comment]
Проверь ещё имена в скиллах, софте. Вообще везде, где текст не должен переноситься.

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
