### ISSUE TITLE
Размер шрифта

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/cv#62]
Шрифт уменьшается при уменьшении ширины экрана. Как думаешь, на смартфонах это будет читаемо?
В хроме есть девайс-бар Ctrl+Shift+M
![r2](https://user-images.githubusercontent.com/31949379/36652998-ecd44696-1ae4-11e8-949f-798865e9c5bc.JPG)

**Comment by ValentinAlexandrovich** [comment]
Исправлено
