### ISSUE TITLE
Ещё раз про Responsive

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/cv#63]
У блоков contact и skills содержимое фиксированного размера. Чем они хуже других блоков, которые растягиваются ?
![r3](https://user-images.githubusercontent.com/31949379/36653484-f23f7f8a-1ae7-11e8-8b4f-d4ba65e145f1.JPG)

**Comment by Geksanit** [comment]
Responsive - как раз означает использование пространства эффективно и при этом выглядеть адекватно. Названные выше блоки этому не соответствуют. (user-card тоже фиксирован, но это не портит его вид)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
