### ISSUE TITLE
Отступы задать родителю или убрать.

### ISSUE THREAD

**Issue by Geksanit** [ValentinAlexandrovich/cv#64]
У нескольких элементов одинаковые отступы слева, если их нужно будет менять, то придется менять в нескольких местах. Лучше задать этот в одном месте. Что отступ регулирует, там его и нужно задавать. В этом конкретном случае отступ меняет позиционирование(визуально) всей колонки. Да и вообще отступ там не нужен.
![r4](https://user-images.githubusercontent.com/31949379/36655094-40ac5368-1af3-11e8-92f2-8a43c3b11b45.jpg)

**Comment by ValentinAlexandrovich** [comment]
Исправлено.
