### ISSUE TITLE
Тернарный оператор

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#8]
```
if options.point_co > x
                        div(class= options.skills + "-assembly-point-check")
                    else
                        div(class= options.skills + "-assembly-point-uncheck")
```
В таких случаях лучше использовать тернарный оператор - даже в таком небольшом примере вместо 4 строчек будет 1.

**Comment by ValentinZadorozhnyy** [comment]
Пробывал записать через тернарный оператор. Код не работает. Теряются переменные, их объявления также не помогает.

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
