### ISSUE TITLE
Адаптив (Responsive)

### ISSUE THREAD

**Issue by Burize** [ValentinAlexandrovich/cv#9]
#Сейчас на самом деле его нет.  Есть 2 блока с фиксированной шириной 525px и они в контейнере с flexbox.  
Адаптив должен задаваться через media query. 
Сделай чтобы макет полностью влезал при ширине экрана 300px ( при этом и при нормальной ширине соответствовал pixelperfect). Сейчас если ширина меньше 525px, то верстка просто выходит за границы видимой области. 

\+ когда верстка переходит в мобильный вариант (схлопывается) для software выводить пункты в одну колонку.

**Comment by ValentinZadorozhnyy** [comment]
Исправлено.
